package com.instantmoney.MoneyServices;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/moneyservice") // This means URL's start with /moneyservice (after Application path)
public class MainController {
	@Autowired // This means to get the bean called senderRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private SenderRepository senderRepository;
	
	@Autowired //this means to get bean called exchangeRepository, you need one for each repo class
	private ExchangeRepository exchangeRepository;

	@GetMapping(path="/addSender") // Map ONLY GET Requests
	public @ResponseBody String addNewSender (@RequestParam String firstName, @RequestParam String lastName, 
			@RequestParam String slocation) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		if (firstName !=null && lastName !=null && slocation !=null) 
		{
			Sender s = new Sender();
			s.setS_first_name(firstName);
			s.setS_last_name(lastName);
			s.setSlocation(slocation);
			senderRepository.save(s);
			return "Saved new Sender";
		}
		else {
			return new String ("FirstName, LastName and Location cannot be NULL");
		}

	}

	@GetMapping(path = "/addExchange") 
	public @ResponseBody String addNewExchange (@RequestParam String exchange)
	{
		boolean hasNonAlphanumeric = exchange.matches("^.*[^a-zA-Z0-9].*$");
		boolean justNumbers = exchange.matches("\\d+");
		
		if (exchange != null && exchange.trim().length()>0 && hasNonAlphanumeric == false && justNumbers ==false)
		{
		Exchange e = new Exchange(); 
		e.setE_name(exchange);
		exchangeRepository.save(e); 
		return "Saved Exchange";
		} 
		else {
			return new String("exchange name can not be null or empty!");
		}
	} 
	
	@GetMapping(path="/allsenders")
	public @ResponseBody Iterable<Sender> getAllSenders() {
		// This returns a JSON or XML with the users
		return senderRepository.findAll();
	}
		
	@GetMapping(path="/allexchanges")
	public @ResponseBody Iterable<Exchange> getAllExchanges() {
			// This returns a JSON or XML with the users
		return exchangeRepository.findAll();
	}
}
